name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Install Node
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Run PHP tests
        run: php artisan test